# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d90c509483c70757c44ca1174237a0cdac65102fe7939f62ade193dfd75d3d3be8528f8288405eb0a011412d40fb0f2bba377cbd2509d60500fe5389bbf6c943

test:
  secret_key_base: a4f998bf09eec3b3d28777ae1430a13b1b07d20d2ca53c42ed7ba39408715dd80a6444d720a1a377c1fa2482185147e75e559dc6d8a94f79d9f56c026af20466

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
